<a href="https://colab.research.google.com/github/1176651368/DL_HR/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
data = np.random.random_sample((3,3))
print(data)

[[0.46438708 0.6010287  0.32287444]
 [0.84597485 0.57722827 0.20662708]
 [0.51460571 0.79574796 0.66091536]]
